### ISSUE TITLE
Error when i do ;;join

### ISSUE THREAD

**Issue by gign0766** [Frederikam/FredBoatMusic#2]
![screenshot_1](https://cloud.githubusercontent.com/assets/15085503/17527984/c8179374-5e6d-11e6-8573-2b719511de33.jpg)

**Comment by Frederikam** [comment]
This is really strange. It appears like it is trying to confirm that it is permitted to join your voice channel, but it seems to think that the member (which happens to be itself) is not in the guild. I'm looking into it.

**Comment by Frederikam** [comment]
A temporary fix might be to reinvite the bot. I discovered this bug earlier today and a restart fixed it.

**Comment by gign0766** [comment]
Reinvite the bot, fix, at least for now, the problem. Thanks for your help.

**Comment by Frederikam** [comment]
Actually, it was probably temporarily fixed because the bot was restarted to get updated. I'm keeping this issue open because this occasionally happens again and again on random servers.

**Comment by gign0766** [comment]
I got the same problem on an other server. I try to reinvite the bot, but he still can't join

**Comment by Frederikam** [comment]
It could be caused by the server running out of memory. I'm writing some changes that should prevent memory usage from old, abandoned music streams.

**Comment by gign0766** [comment]
I hope this will fix he problem. For now, the bot works again.

**Comment by Frederikam** [comment]
I don't have the time to fix these issues right now due to school, so I will leave the bot vulnerable as I sleep. Expect a restart in a sec in an attempt to prevent more OOM failures.

**Comment by Frederikam** [comment]
This should now be fixed with the currently live version of FredBoat. Reopen this issue if it reoccurs.
